language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
# command to install dependencies
install: python setup.py install && pip install pytest markupsafe inflector==1.6 orm>=1.0.3
# command to run tests, e.g. python setup.py test
script: py.test tests
